import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { SideNav } from './ui/sidenav'

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
})
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`bg-slate-200 text-stone-900 ${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<header className='flex bg-blue-500 text-white p-1 shadow-md'>
					<div className='flex items-center ml-4'>
						<div className='pear'></div>
						<h1 className='text-xl ml-2'>Healthy Life App</h1>
					</div>
				</header>
				<div className='flex flex-col md:flex-row md:overflow-hidden'>
					<div className='w-full flex-none md:w-64'>
						<SideNav />
					</div>
					<div className='flex-grow md:overflow-y-auto md:p-12'>
						{children}
					</div>
				</div>
			</body>
		</html>
	)
}
